### ISSUE TITLE
livretinfo/form.css

### ISSUE THREAD

**Issue by PavloKovalov** [seotoaster-team/seotoaster#40]
https://github.com/seotoaster-team/seotoaster/tree/develop/livretinfo
 I was waiting for it past few years! Thanks, finally somebody added it to the repo! 

:crying_cat_face: :laughing: :sunglasses: :bicyclist: :shipit: :shit: :facepunch: :rocket: :dancers: :poodle:

**Comment by theneiam** [comment]
Finally! Good job guys! :raised_hand:

**Comment by seotoaster-team** [comment]
Removed

**Comment by PavloKovalov** [comment]
it's not fair
:cry:
